import type { SceneDefinition } from '@gremuchaya/domain';

import {
  cctvPreset,
  defineScene,
  dossierPreset,
  mapPreset,
  newsPreset,
  osintPreset,
  patchCue,
  satellitePreset,
  setModuleCue,
  systemTablePreset,
  vehiclePreset,
} from './sceneBuilders';

const apartmentCameras = cctvPreset({
  assetId: 'cctv-apartment-hallway',
  cameraId: 'APT-01',
  location: 'КВАРТИРА / ПРИХОЖАЯ',
  archive: true,
  mosaic: ['cctv-apartment-hallway', 'cctv-apartment-kitchen'],
});

const coverScreen = systemTablePreset('СИСТЕМНЫЙ МОНИТОРИНГ / КАНАЛЫ');

export const september14Scenes: readonly SceneDefinition[] = [
  defineScene({
    id: 's04-01b',
    episode: 4,
    scene: '1-b',
    shootDate: '2026-09-14',
    title: 'Мурзаев',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Досье Абдулджабара Мурзаева с подтверждёнными фактами и двумя ракурсами.',
    screens: {
      'wall-center': dossierPreset('murzaev', 'АБДУЛДЖАБАР МУРЗАЕВ', {
        status: 'ФЕДЕРАЛЬНЫЙ РОЗЫСК / С 09.2016',
        category: 'АКТИВНЫЙ ЧЛЕН ДАРГИНСКОГО ПОДПОЛЬЯ',
        facts: ['Подготовка в сирийских лагерях', 'Федеральный розыск с сентября 2016'],
        assets: ['photo-murzaev-front', 'photo-murzaev-profile'],
      }),
    },
    cues: [
      patchCue('profile', 'Профиль', 'wall-center', {
        portraitAssetIds: ['photo-murzaev-profile', 'photo-murzaev-front'],
      }),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: ['hwan-main'],
    requiredAssetIds: ['photo-murzaev-front', 'photo-murzaev-profile'],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's00-01',
    episode: 0,
    scene: 'МАГАЗИН',
    shootDate: '2026-09-14',
    title: 'Магазин / CCTV',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Камера магазина с продавцом, Чумаковой и управляемым аудиоканалом.',
    screens: {
      'wall-center': cctvPreset({
        assetId: 'cctv-shop-chumakova',
        cameraId: 'SHOP-02',
        location: 'ТОРГОВЫЙ ЗАЛ',
        archive: true,
      }),
    },
    cues: [
      patchCue('unmute', 'Включить аудиоканал', 'wall-center', {
        muted: false,
        audioEnabled: true,
      }),
      patchCue('freeze', 'Freeze', 'wall-center', { playing: false }),
      patchCue('face', 'Выделить лицо Чумаковой', 'wall-center', {
        location: 'ЧУМАКОВА / FACE SELECT',
      }),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: [],
    requiredAssetIds: ['cctv-shop-chumakova'],
    optionalAssetIds: [],
    notes: ['Рабочий ID s00-01: источник не содержит номера эпизода и сцены.'],
  }),
  defineScene({
    id: 's05-12',
    episode: 5,
    scene: '12',
    shootDate: '2026-09-14',
    title: 'Бологое',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Карта Тверской области с новой SIM и нулевой историей.',
    screens: {
      'wall-center': mapPreset({
        assetId: 'map-tver-bologoe',
        title: 'ТВЕРСКАЯ ОБЛАСТЬ / БОЛОГОЕ',
        markerLabel: 'СИГНАЛ БС',
        signal: 'SIM: НОВАЯ / ИСТОРИЯ: 0',
        address: 'БОЛОГОЕ',
      }),
    },
    cues: [
      patchCue('ping', 'Обновить сигнал БС', 'wall-center', {
        readout: {
          object: 'СИГНАЛ БС',
          speed: '0 КМ/Ч',
          signal: 'SIM: НОВАЯ / ИСТОРИЯ: 0',
          address: 'БОЛОГОЕ',
        },
      }),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: [],
    requiredAssetIds: ['map-tver-bologoe'],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's05-19',
    episode: 5,
    scene: '19',
    shootDate: '2026-09-14',
    title: 'Рыбаков / дайвинг',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'OSINT-подборка: пляж, снаряжение, одиночные и групповые фотографии.',
    screens: {
      'hwan-main': osintPreset('РЫБАКОВ / ДАЙВИНГ', 'RESULTS', [
        'photo-rybakov-beach',
        'photo-rybakov-gear',
        'photo-rybakov-alone',
        'photo-rybakov-group',
      ]),
    },
    cues: [
      setModuleCue(
        'profile',
        'Открыть профиль',
        'hwan-main',
        osintPreset('РЫБАКОВ / ДАЙВИНГ', 'PROFILE', [
          'photo-rybakov-beach',
          'photo-rybakov-gear',
          'photo-rybakov-alone',
          'photo-rybakov-group',
        ]),
      ),
      patchCue('select-group', 'Фото в компании', 'hwan-main', {
        stage: 'SELECT',
        selectedAssetId: 'photo-rybakov-group',
      }),
    ],
    requiredScreens: ['hwan-main'],
    optionalScreens: ['wall-center'],
    requiredAssetIds: [
      'photo-rybakov-beach',
      'photo-rybakov-gear',
      'photo-rybakov-alone',
      'photo-rybakov-group',
    ],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's06-17',
    episode: 6,
    scene: '17',
    shootDate: '2026-09-14',
    title: 'Поток машин',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Распознавание нескольких машин с выбором одного активного объекта.',
    screens: { 'wall-center': vehiclePreset('video-vehicle-stream', 'ЦЕЛЬ / 07') },
    cues: [
      patchCue('lock', 'Зафиксировать цель 07', 'wall-center', {
        title: 'ЦЕЛЬ ЗАФИКСИРОВАНА / 07',
      }),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: ['hwan-main'],
    requiredAssetIds: ['video-vehicle-stream'],
    optionalAssetIds: [],
    notes: ['Tracking boxes описаны в payload.'],
  }),
  defineScene({
    id: 's08-28',
    episode: 8,
    scene: '28',
    shootDate: '2026-09-14',
    title: 'Новости + CCTV на фоне',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Передний монитор показывает новости, экран Хван — мозаику уличных камер.',
    screens: {
      'wall-center': newsPreset('ОПЕРАТИВНЫЙ ЭФИР', 'news-background'),
      'hwan-main': cctvPreset({
        assetId: 'cctv-street-01',
        cameraId: 'STREET-MX',
        location: 'УЛИЧНЫЕ КАМЕРЫ',
        mosaic: ['cctv-street-01', 'cctv-street-02', 'cctv-street-03', 'cctv-street-04'],
      }),
    },
    cues: [patchCue('camera-3', 'Камера 03', 'hwan-main', { selectedCamera: 2 })],
    requiredScreens: ['wall-center', 'hwan-main'],
    optionalScreens: [],
    requiredAssetIds: [
      'news-background',
      'cctv-street-01',
      'cctv-street-02',
      'cctv-street-03',
      'cctv-street-04',
    ],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's15-41',
    episode: 15,
    scene: '41',
    shootDate: '2026-09-14',
    title: 'Людмила Фролова',
    location: 'HQ',
    sourceLevel: 'derived',
    description: 'Допустимая derived-карточка поиска и связанных материалов Людмилы Фроловой.',
    screens: {
      'hwan-main': dossierPreset('lyudmila-frolova', 'ЛЮДМИЛА ФРОЛОВА', {
        status: 'ПОИСК В МАТЕРИАЛАХ',
        assets: ['photo-lyudmila-frolova'],
      }),
    },
    cues: [
      setModuleCue(
        'materials',
        'Связанные фотографии',
        'hwan-main',
        osintPreset('ЛЮДМИЛА ФРОЛОВА', 'RESULTS', [
          'photo-lyudmila-frolova',
          'photo-frolova-family',
        ]),
      ),
    ],
    requiredScreens: ['hwan-main'],
    optionalScreens: ['wall-center'],
    requiredAssetIds: ['photo-lyudmila-frolova'],
    optionalAssetIds: ['photo-frolova-family'],
    notes: ['Derived: точное экранное содержимое источником не задано.'],
  }),
  defineScene({
    id: 's16-38',
    episode: 16,
    scene: '38',
    shootDate: '2026-09-14',
    title: 'Секретное наблюдение / cover',
    location: 'HQ',
    sourceLevel: 'kpp',
    description:
      'Видео квартиры мгновенно заменяется безопасной системной таблицей при входе Кириллова.',
    screens: { 'hwan-main': apartmentCameras },
    cues: [setModuleCue('cover', 'Кириллов входит / COVER', 'hwan-main', coverScreen)],
    requiredScreens: ['hwan-main'],
    optionalScreens: ['wall-center'],
    requiredAssetIds: ['cctv-apartment-hallway', 'cctv-apartment-kitchen'],
    optionalAssetIds: [],
    notes: ['Cover применяется синхронно; целевая задержка не более 150 ms.'],
  }),
  defineScene({
    id: 's16-42',
    episode: 16,
    scene: '42',
    shootDate: '2026-09-14',
    title: 'Квартира',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Оператор переключает камеры прихожей и кухни.',
    screens: { 'wall-center': apartmentCameras },
    cues: [
      patchCue('hallway', 'Прихожая', 'wall-center', {
        selectedCamera: 0,
        cameraId: 'APT-01',
        location: 'КВАРТИРА / ПРИХОЖАЯ',
        assetId: 'cctv-apartment-hallway',
      }),
      patchCue('kitchen', 'Кухня', 'wall-center', {
        selectedCamera: 1,
        cameraId: 'APT-02',
        location: 'КВАРТИРА / КУХНЯ',
        assetId: 'cctv-apartment-kitchen',
      }),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: [],
    requiredAssetIds: ['cctv-apartment-hallway', 'cctv-apartment-kitchen'],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's16-44',
    episode: 16,
    scene: '44',
    shootDate: '2026-09-14',
    title: 'Квартира / выход людей',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Кудашов и девушки уходят; Караев и Никольский возвращаются на кухню.',
    screens: { 'wall-center': apartmentCameras },
    cues: [
      patchCue('leave', 'Кудашов и девушки уходят', 'wall-center', {
        selectedCamera: 0,
        location: 'ПРИХОЖАЯ / ВЫХОД',
      }),
      patchCue('return', 'Караев и Никольский на кухне', 'wall-center', {
        selectedCamera: 1,
        location: 'КУХНЯ / ВОЗВРАЩЕНИЕ',
      }),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: [],
    requiredAssetIds: ['cctv-apartment-hallway', 'cctv-apartment-kitchen'],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's05-32',
    episode: 5,
    scene: '32',
    shootDate: '2026-09-14',
    title: 'Гольцов / начало',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Метка на Савватьевском шоссе сменяется задачей спутниковому сенсору.',
    screens: {
      'wall-center': mapPreset({
        assetId: 'map-savvatievskoe',
        title: 'САВВАТЬЕВСКОЕ ШОССЕ',
        markerLabel: 'ГОЛЬЦОВ',
        speed: '68 КМ/Ч',
      }),
    },
    cues: [
      setModuleCue(
        'sensor',
        'Доступность спутника / tasking',
        'wall-center',
        satellitePreset({
          assetId: 'sat-goltsov-tasking',
          mode: 'ACQUIRE',
          targetLabel: 'ГОЛЬЦОВ',
          quality: 76,
        }),
      ),
      patchCue('acquired', 'Сенсор захватил цель', 'wall-center', {
        mode: 'TRACK',
        signalQuality: 91,
        zoom: 2,
      }),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: ['hwan-main'],
    requiredAssetIds: ['map-savvatievskoe', 'sat-goltsov-tasking'],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's05-36',
    episode: 5,
    scene: '36',
    shootDate: '2026-09-14',
    title: 'Спутниковый zoom',
    location: 'HQ',
    sourceLevel: 'kpp',
    description:
      'Цифровые часы фиксируют паузу около десяти минут, затем спутник приближает лесную развилку.',
    screens: { 'wall-center': systemTablePreset('ОЖИДАНИЕ СЕНСОРА / 00:10:00') },
    cues: [
      setModuleCue(
        'blur',
        'Мутный ч/б канал',
        'wall-center',
        satellitePreset({
          assetId: 'sat-goltsov-forest',
          mode: 'ACQUIRE',
          targetLabel: 'ЛЕСНОЙ МАССИВ',
          quality: 38,
        }),
      ),
      patchCue('forest', 'Zoom / лес / развилка', 'wall-center', {
        mode: 'ZOOM',
        zoom: 4,
        signalQuality: 62,
      }),
      patchCue('vehicle', 'Машина', 'wall-center', {
        mode: 'TRACK',
        zoom: 6,
        target: { x: 0.58, y: 0.52, label: 'АВТОМОБИЛЬ' },
      }),
      patchCue('person', 'Человек', 'wall-center', {
        zoom: 8,
        target: { x: 0.61, y: 0.48, label: 'ЧЕЛОВЕК' },
      }),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: [],
    requiredAssetIds: ['sat-goltsov-forest'],
    optionalAssetIds: [],
    notes: ['Критическая последовательность clock → optical zoom.'],
  }),
  defineScene({
    id: 's05-37a',
    episode: 5,
    scene: '37a',
    shootDate: '2026-09-14',
    title: 'Под кронами',
    location: 'HQ',
    sourceLevel: 'kpp',
    description:
      'Оптическая цель теряется под кронами, интерфейс переключается на мобильную метку.',
    screens: {
      'wall-center': satellitePreset({
        assetId: 'sat-goltsov-canopy',
        mode: 'LOST',
        targetLabel: 'ГОЛЬЦОВ',
        quality: 0,
        lossStage: 'lost',
      }),
    },
    cues: [
      setModuleCue(
        'mobile',
        'Mobile tracker',
        'wall-center',
        mapPreset({
          assetId: 'map-goltsov-mobile',
          title: 'МОБИЛЬНЫЙ TRACKER',
          markerLabel: 'ГОЛЬЦОВ',
          signal: '46%',
        }),
      ),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: [],
    requiredAssetIds: ['sat-goltsov-canopy', 'map-goltsov-mobile'],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's05-40b',
    episode: 5,
    scene: '40b',
    shootDate: '2026-09-14',
    title: 'Избушка',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Спутниковый канал фиксирует охотничью избушку, Гольцова и Гришу у машины.',
    screens: {
      'wall-center': satellitePreset({
        assetId: 'sat-hunting-cabin',
        mode: 'TRACK',
        targetLabel: 'ОХОТНИЧЬЯ ИЗБУШКА',
        zoom: 4,
      }),
    },
    cues: [
      patchCue('people', 'Гольцов и Гриша к машине', 'wall-center', {
        zoom: 6,
        target: { x: 0.64, y: 0.57, label: 'ГОЛЬЦОВ / ГРИША' },
      }),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: [],
    requiredAssetIds: ['sat-hunting-cabin'],
    optionalAssetIds: [],
    notes: [],
  }),
];
