import type { SceneDefinition } from '@gremuchaya/domain';

import {
  audioPreset,
  cctvPreset,
  defineScene,
  dossierPreset,
  interrogationPreset,
  mapPreset,
  newsPreset,
  osintPreset,
  patchCue,
  photoArchivePreset,
  securityPreset,
  setModuleCue,
} from './sceneBuilders';

export const september15to19Scenes: readonly SceneDefinition[] = [
  defineScene({
    id: 's09-56',
    episode: 9,
    scene: '56',
    shootDate: '2026-09-15',
    title: 'Новости / Бондарев',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Новости сменяются материалами дела и фотороботом неустановленного Бондарева.',
    screens: { 'wall-center': newsPreset('НОВОСТИ / БОНДАРЕВ', 'news-bondarev') },
    cues: [
      setModuleCue(
        'case',
        'Материалы дела',
        'wall-center',
        photoArchivePreset('МАТЕРИАЛЫ ДЕЛА', [
          'photo-wedding',
          'photo-chernogor',
          'photo-shcherba',
          'photo-limousine-scene',
        ]),
      ),
      patchCue('shcherba', 'Щерба', 'wall-center', { selectedIndex: 2 }),
      setModuleCue(
        'sketch',
        'Фоторобот Бондарева',
        'wall-center',
        dossierPreset('bondarev-unknown', 'НЕУСТАНОВЛЕННОЕ ЛИЦО', {
          status: 'ФОТОРОБОТ / УСЫ',
          assets: ['photo-bondarev-sketch'],
        }),
      ),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: ['hwan-main'],
    requiredAssetIds: [
      'news-bondarev',
      'photo-wedding',
      'photo-chernogor',
      'photo-shcherba',
      'photo-limousine-scene',
      'photo-bondarev-sketch',
    ],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's08-31',
    episode: 8,
    scene: '31',
    shootDate: '2026-09-16',
    title: 'Silver-94',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Видео проходит через zoom надписи Silver-94 к поиску, профилю и фотографии.',
    screens: {
      'wall-center': cctvPreset({
        assetId: 'video-silver94',
        cameraId: 'SRC-94',
        location: 'ПОЛЕВОЙ МАТЕРИАЛ',
        archive: true,
      }),
    },
    cues: [
      patchCue('zoom', 'ZOOM SILVER-94', 'wall-center', {
        playing: false,
        location: 'SILVER-94 / CROP',
      }),
      setModuleCue(
        'search',
        'WEB SEARCH',
        'hwan-main',
        osintPreset('SILVER-94', 'SEARCH', ['photo-silver94-miner']),
      ),
      setModuleCue(
        'results',
        'RESULTS',
        'hwan-main',
        osintPreset('SILVER-94', 'RESULTS', ['photo-silver94-miner']),
      ),
      setModuleCue(
        'profile',
        'PROFILE',
        'hwan-main',
        osintPreset('SILVER-94', 'PROFILE', ['photo-silver94-miner']),
      ),
      setModuleCue(
        'photo',
        'PHOTO',
        'wall-center',
        osintPreset('SILVER-94', 'PHOTO', ['photo-silver94-miner']),
      ),
    ],
    requiredScreens: ['wall-center', 'hwan-main'],
    optionalScreens: [],
    requiredAssetIds: ['video-silver94', 'photo-silver94-miner'],
    optionalAssetIds: [],
    notes: ['Фото: каска, налобный фонарь, грязное лицо.'],
  }),
  defineScene({
    id: 's08-33',
    episode: 8,
    scene: '33',
    shootDate: '2026-09-16',
    title: 'Козицкий / Silver-94',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Пленный Козицкий на стене; Хван увеличивает маркировку Silver-94.',
    screens: {
      'wall-center': cctvPreset({
        assetId: 'video-kozitsky-captive',
        cameraId: 'FIELD-08',
        location: 'КОЗИЦКИЙ / ПЛЕННЫЙ',
        archive: true,
      }),
      'hwan-main': osintPreset('SILVER-94', 'SELECT', ['crop-silver94']),
    },
    cues: [
      patchCue('crop', 'Crop / zoom / SILVER-94', 'hwan-main', {
        selectedAssetId: 'crop-silver94',
        stage: 'PHOTO',
      }),
    ],
    requiredScreens: ['wall-center', 'hwan-main'],
    optionalScreens: [],
    requiredAssetIds: ['video-kozitsky-captive', 'crop-silver94'],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's08-36',
    episode: 8,
    scene: '36',
    shootDate: '2026-09-16',
    title: 'ГЭС',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Объектовое досье ГЭС: территория, схема, архив и отметка Silver-94.',
    screens: {
      'wall-center': dossierPreset('hydropower-station', 'ГИДРОЭЛЕКТРОСТАНЦИЯ', {
        status: 'ОБЪЕКТОВОЕ ДОСЬЕ',
        category: 'КРИТИЧЕСКАЯ ИНФРАСТРУКТУРА',
        facts: ['Территория', 'Технологическая схема', 'Архивные ракурсы', 'Маркер SILVER-94'],
        assets: [
          'sat-hydropower-station',
          'scheme-hydropower-station',
          'archive-hydropower-station',
        ],
      }),
    },
    cues: [
      patchCue('scheme', 'Схема объекта', 'wall-center', {
        portraitAssetIds: [
          'scheme-hydropower-station',
          'sat-hydropower-station',
          'archive-hydropower-station',
        ],
      }),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: ['hwan-main'],
    requiredAssetIds: [
      'sat-hydropower-station',
      'scheme-hydropower-station',
      'archive-hydropower-station',
    ],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's16-49',
    episode: 16,
    scene: '49',
    shootDate: '2026-09-16',
    title: 'Камера штаба',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Состояние внутренней камеры HQ-01 отключается и восстанавливается.',
    screens: { 'hwan-main': securityPreset('ONLINE') },
    cues: [
      setModuleCue('disable', 'LINK DISABLED', 'hwan-main', securityPreset('LINK DISABLED')),
      setModuleCue('reconnect', 'RECONNECTING', 'hwan-main', securityPreset('RECONNECTING')),
      setModuleCue('online', 'ONLINE', 'hwan-main', securityPreset('ONLINE')),
    ],
    requiredScreens: ['hwan-main'],
    optionalScreens: [],
    requiredAssetIds: ['cctv-hq-internal'],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's03-11',
    episode: 3,
    scene: '11',
    shootDate: '2026-09-18',
    title: 'Кириллов / проектор',
    location: 'KIRILLOV',
    sourceLevel: 'kpp',
    description: 'Лицо Липатова и глобальный маршрут через шесть регионов мира.',
    screens: {
      'wall-center': mapPreset({
        assetId: 'map-world-lipatov',
        title: 'ГЛОБАЛЬНЫЙ МАРШРУТ / ЛИПАТОВ',
        markerLabel: 'ЛИПАТОВ',
        address: 'ОКЕАНИЯ → ЯПОНИЯ → АФРИКА → ЕВРОПА → АВСТРАЛИЯ → АЗИЯ',
      }),
      'kirillov-desk': dossierPreset('lipatov', 'ЛИПАТОВ', { assets: ['photo-lipatov'] }),
    },
    cues: [
      patchCue('japan', 'Япония', 'wall-center', {
        markers: [
          { id: 'object-01', x: 0.82, y: 0.35, label: 'ЯПОНИЯ', active: true, pulse: true },
        ],
      }),
      patchCue('europe', 'Европа', 'wall-center', {
        markers: [
          { id: 'object-01', x: 0.51, y: 0.31, label: 'ЕВРОПА', active: true, pulse: true },
        ],
      }),
      patchCue('asia', 'Азия', 'wall-center', {
        markers: [{ id: 'object-01', x: 0.71, y: 0.3, label: 'АЗИЯ', active: true, pulse: true }],
      }),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: ['kirillov-desk'],
    requiredAssetIds: ['map-world-lipatov', 'photo-lipatov'],
    optionalAssetIds: [],
    notes: ['Проектор физически привязан к логическому экрану wall-center.'],
  }),
  defineScene({
    id: 's13-11',
    episode: 13,
    scene: '11',
    shootDate: '2026-09-18',
    title: 'Люда',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Сравнение фотографий Люды до похищения и после.',
    screens: {
      'wall-center': photoArchivePreset(
        'ЛЮДА / ДО — ПОСЛЕ',
        ['photo-lyuda-before', 'photo-lyuda-after'],
        0,
        true,
      ),
    },
    cues: [patchCue('after', 'После', 'wall-center', { selectedIndex: 1 })],
    requiredScreens: ['wall-center'],
    optionalScreens: [],
    requiredAssetIds: ['photo-lyuda-before', 'photo-lyuda-after'],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's15-11',
    episode: 15,
    scene: '11/12',
    shootDate: '2026-09-18',
    title: 'Караев / Борис',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Архив CCTV: Караев душит Бориса, Кириллов оттаскивает его.',
    screens: {
      'wall-center': cctvPreset({
        assetId: 'cctv-karaev-boris',
        cameraId: 'APT-07',
        location: 'КВАРТИРА',
        archive: true,
      }),
    },
    cues: [
      patchCue('attack', 'Караев душит Бориса', 'wall-center', {
        timestamp: '18.09.2026 21:44:12',
      }),
      patchCue('kirillov', 'Кириллов оттаскивает', 'wall-center', {
        timestamp: '18.09.2026 21:44:19',
      }),
      patchCue('freeze', 'Freeze', 'wall-center', { playing: false }),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: [],
    requiredAssetIds: ['cctv-karaev-boris'],
    optionalAssetIds: [],
    notes: ['Одна конфигурация покрывает сцены 15-11 и 15-12.'],
  }),
  defineScene({
    id: 's03-31',
    episode: 3,
    scene: '31',
    shootDate: '2026-09-19',
    title: 'Два монитора допросной',
    location: 'INTERROGATION',
    sourceLevel: 'kpp',
    description: 'Синхронизированные CCTV и аудиограмма допросной.',
    screens: {
      'interrogation-video': interrogationPreset('cctv-interrogation-room'),
      'interrogation-audio': audioPreset(true),
    },
    cues: [
      patchCue('sync', 'Синхронизировать timecode', 'interrogation-video', {
        timestamp: '19.09.2026 14:32:21',
      }),
      patchCue('audio-sync', 'Аудио timecode', 'interrogation-audio', { timestamp: '14:32:21:00' }),
    ],
    requiredScreens: ['interrogation-video', 'interrogation-audio'],
    optionalScreens: [],
    requiredAssetIds: ['cctv-interrogation-room'],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's04-26a',
    episode: 4,
    scene: '26a',
    shootDate: '2026-09-19',
    title: 'Макеев',
    location: 'INTERROGATION',
    sourceLevel: 'kpp',
    description: 'Отдельная вставка архива допроса Макеева на монитор штаба.',
    screens: {
      'wall-center': interrogationPreset('video-makeev-interrogation', 'КОМНАТА / МАКЕЕВ'),
    },
    cues: [patchCue('freeze', 'Зафиксировать кадр', 'wall-center', { playing: false })],
    requiredScreens: ['wall-center'],
    optionalScreens: [],
    requiredAssetIds: ['video-makeev-interrogation'],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's04-09a',
    episode: 4,
    scene: '9a',
    shootDate: '2026-09-19',
    title: 'Чумакова',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'CCTV фиксирует, как сотрудники выводят заторможенную Чумакову.',
    screens: {
      'wall-center': cctvPreset({
        assetId: 'cctv-chumakova-escort',
        cameraId: 'CORRIDOR-09',
        location: 'СЛУЖЕБНЫЙ КОРИДОР',
        archive: true,
      }),
    },
    cues: [
      patchCue('escort', 'Сотрудники выводят Чумакову', 'wall-center', {
        timestamp: '19.09.2026 19:08:44',
      }),
      patchCue('freeze', 'Freeze', 'wall-center', { playing: false }),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: [],
    requiredAssetIds: ['cctv-chumakova-escort'],
    optionalAssetIds: [],
    notes: [],
  }),
];
