import type { SceneDefinition } from '@gremuchaya/domain';

import {
  cctvPreset,
  commsPreset,
  defineScene,
  graphPreset,
  mapPreset,
  patchCue,
  satellitePreset,
  setModuleCue,
  systemTablePreset,
} from './sceneBuilders';

const lipatovRoute = mapPreset({
  assetId: 'map-spb-kad-shushary',
  title: 'МАРШРУТ / САНКТ-ПЕТЕРБУРГ — ШУШАРЫ',
  markerLabel: 'ЛИПАТОВ',
  speed: '74 КМ/Ч',
  signal: 'УСТОЙЧИВЫЙ',
  address: 'КАД / НАПРАВЛЕНИЕ ШУШАРЫ',
});

const moneyTracker = mapPreset({
  assetId: 'map-money-tracker',
  title: 'ДВИЖУТСЯ ДЕНЬГИ',
  markerLabel: 'МЕТКА-01',
  speed: '42 КМ/Ч',
  signal: '87%',
});

export const september13Scenes: readonly SceneDefinition[] = [
  defineScene({
    id: 's02-38',
    episode: 2,
    scene: '38',
    shootDate: '2026-09-13',
    title: 'Липатов выезжает',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Оптический канал фиксирует машину, выезжающую из ворот.',
    screens: {
      'wall-center': satellitePreset({
        assetId: 'sat-lipatov-gates',
        mode: 'TRACK',
        targetLabel: 'АВТОМОБИЛЬ ЛИПАТОВА',
      }),
    },
    cues: [
      patchCue('exit', 'Машина выходит из ворот', 'wall-center', { zoom: 2.4, signalQuality: 94 }),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: ['hwan-main'],
    requiredAssetIds: ['sat-lipatov-gates'],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's02-40',
    episode: 2,
    scene: '40',
    shootDate: '2026-09-13',
    title: 'Противонаблюдение',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Четыре конфигурируемые фазы контрнаблюдения за автомобилем.',
    screens: {
      'wall-center': cctvPreset({
        assetId: 'video-counter-surveillance',
        cameraId: 'OPT-02',
        location: 'ДОРОЖНЫЙ КОНТУР',
        archive: true,
      }),
    },
    cues: [
      patchCue('exit', 'Съезд', 'wall-center', { timestamp: '13.09.2026 12:41:08', playing: true }),
      patchCue('turn', 'Разворот', 'wall-center', { timestamp: '13.09.2026 12:42:31' }),
      patchCue('return', 'Возвращение', 'wall-center', { timestamp: '13.09.2026 12:43:19' }),
      patchCue('moving', 'Движение', 'wall-center', { timestamp: '13.09.2026 12:44:02' }),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: [],
    requiredAssetIds: ['video-counter-surveillance'],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's02-42',
    episode: 2,
    scene: '42',
    shootDate: '2026-09-13',
    title: 'Маршрут',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Карта Санкт-Петербурга и КАД с движущейся меткой на Шушары.',
    screens: { 'wall-center': lipatovRoute },
    cues: [
      patchCue('kad', 'Выход на КАД', 'wall-center', {
        markers: [
          { id: 'object-01', x: 0.47, y: 0.46, label: 'ЛИПАТОВ', active: true, pulse: true },
        ],
      }),
      patchCue('shushary', 'Направление Шушары', 'wall-center', {
        markers: [
          { id: 'object-01', x: 0.69, y: 0.63, label: 'ЛИПАТОВ', active: true, pulse: true },
        ],
      }),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: ['hwan-main'],
    requiredAssetIds: ['map-spb-kad-shushary'],
    optionalAssetIds: [],
    notes: ['Маршрут задаётся конфигурацией маркеров.'],
  }),
  defineScene({
    id: 's02-44',
    episode: 2,
    scene: '44',
    shootDate: '2026-09-13',
    title: 'Пешеходный мост',
    location: 'HQ',
    sourceLevel: 'kpp',
    description:
      'Сначала метка пересекает мост, затем включается оптический канал с Липатовым и чемоданом.',
    screens: {
      'wall-center': mapPreset({
        assetId: 'map-pedestrian-bridge',
        title: 'ПЕШЕХОДНЫЙ МОСТ',
        markerLabel: 'МЕТКА-01',
        x: 0.28,
        y: 0.52,
      }),
    },
    cues: [
      patchCue('crossing', 'Метка проходит мост', 'wall-center', {
        markers: [
          { id: 'object-01', x: 0.7, y: 0.49, label: 'МЕТКА-01', active: true, pulse: true },
        ],
      }),
      setModuleCue(
        'optical',
        'Оптический канал',
        'wall-center',
        satellitePreset({
          assetId: 'sat-lipatov-briefcase',
          mode: 'ZOOM',
          targetLabel: 'ЛИПАТОВ / ЧЕМОДАН',
          zoom: 4.5,
        }),
      ),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: [],
    requiredAssetIds: ['map-pedestrian-bridge', 'sat-lipatov-briefcase'],
    optionalAssetIds: [],
    notes: ['Критический переход map → satellite.'],
  }),
  defineScene({
    id: 's02-50',
    episode: 2,
    scene: '50',
    shootDate: '2026-09-13',
    title: 'Липатов идёт обратно',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Тот же медиаканал показывает обратную фазу движения.',
    screens: {
      'wall-center': cctvPreset({
        assetId: 'video-lipatov-return',
        cameraId: 'OPT-03',
        location: 'ПЕШЕХОДНЫЙ МОСТ',
        archive: true,
      }),
    },
    cues: [
      patchCue('return', 'Обратное движение', 'wall-center', {
        playing: true,
        timestamp: '13.09.2026 13:09:45',
      }),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: [],
    requiredAssetIds: ['video-lipatov-return'],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's02-52',
    episode: 2,
    scene: '52',
    shootDate: '2026-09-13',
    title: 'Движутся деньги',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Мобильный tracker отображает метку, скорость, направление и сигнал.',
    screens: { 'wall-center': moneyTracker },
    cues: [
      patchCue('move', 'Обновить положение', 'wall-center', {
        markers: [
          {
            id: 'object-01',
            x: 0.64,
            y: 0.42,
            label: 'МЕТКА-01',
            active: true,
            pulse: true,
            heading: 72,
          },
        ],
      }),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: ['hwan-main'],
    requiredAssetIds: ['map-money-tracker'],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's02-58',
    episode: 2,
    scene: '58',
    shootDate: '2026-09-13',
    title: 'КамАЗ / потеря спутника',
    location: 'HQ',
    sourceLevel: 'kpp',
    description:
      'Последовательная деградация спутникового канала с переходом на мобильный tracker.',
    screens: {
      'wall-center': satellitePreset({
        assetId: 'sat-kamaz',
        mode: 'TRACK',
        targetLabel: 'КАМАЗ',
        lossStage: 'clean',
      }),
    },
    cues: [
      patchCue('clean', 'CLEAN', 'wall-center', {
        mode: 'TRACK',
        lossStage: 'clean',
        signalQuality: 93,
      }),
      patchCue('light', 'LIGHT INTERFERENCE', 'wall-center', {
        mode: 'DEGRADED',
        lossStage: 'light',
        signalQuality: 61,
      }),
      patchCue('heavy', 'HEAVY INTERFERENCE', 'wall-center', {
        mode: 'DEGRADED',
        lossStage: 'heavy',
        signalQuality: 24,
      }),
      patchCue('lost', 'SIGNAL LOST', 'wall-center', {
        mode: 'LOST',
        lossStage: 'lost',
        signalQuality: 0,
      }),
      setModuleCue(
        'tracker',
        'TRACKER ONLY',
        'wall-center',
        mapPreset({
          assetId: 'map-kamaz-tracker',
          title: 'МОБИЛЬНЫЙ TRACKER',
          markerLabel: 'МЕТКА-01',
          signal: '31%',
        }),
      ),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: [],
    requiredAssetIds: ['sat-kamaz', 'map-kamaz-tracker'],
    optionalAssetIds: [],
    notes: ['Критическая пятиступенчатая анимация.'],
  }),
  defineScene({
    id: 's03-04',
    episode: 3,
    scene: '4',
    shootDate: '2026-09-13',
    title: 'Перехват телефона',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Перехват входящего соединения абонента Рогожин.',
    screens: { 'wall-center': commsPreset('РОГОЖИН', 'RINGING') },
    cues: [
      setModuleCue(
        'ringing',
        'Входящее соединение',
        'wall-center',
        commsPreset('РОГОЖИН', 'RINGING'),
      ),
      setModuleCue(
        'connecting',
        'Установка соединения',
        'wall-center',
        commsPreset('РОГОЖИН', 'CONNECTING'),
      ),
      setModuleCue('connected', 'Канал открыт', 'wall-center', commsPreset('РОГОЖИН', 'CONNECTED')),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: [],
    requiredAssetIds: [],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's03-33',
    episode: 3,
    scene: '33',
    shootDate: '2026-09-13',
    title: 'Схема телефонных связей',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Граф телефонных связей расширяется с четырёх до восьми узлов.',
    screens: { 'wall-center': graphPreset(false) },
    cues: [setModuleCue('expand', 'Расширить выборку', 'wall-center', graphPreset(true))],
    requiredScreens: ['wall-center'],
    optionalScreens: ['hwan-main'],
    requiredAssetIds: [],
    optionalAssetIds: [],
    notes: ['Граф конфигурируемый; направление и weight хранятся в edges.'],
  }),
  defineScene({
    id: 's09-59',
    episode: 9,
    scene: '59',
    shootDate: '2026-09-13',
    title: 'Спутниковая карта',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Повторно используется штатный спутниковый preset.',
    screens: {
      'wall-center': satellitePreset({
        assetId: 'sat-region-wide',
        mode: 'ACQUIRE',
        targetLabel: 'ОБЪЕКТ',
      }),
    },
    cues: [patchCue('track', 'Захват объекта', 'wall-center', { mode: 'TRACK', zoom: 2.2 })],
    requiredScreens: ['wall-center'],
    optionalScreens: [],
    requiredAssetIds: ['sat-region-wide'],
    optionalAssetIds: [],
    notes: ['Новый дизайн не вводится.'],
  }),
  defineScene({
    id: 's10-44',
    episode: 10,
    scene: '44',
    shootDate: '2026-09-13',
    title: 'Ленинградская область',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Региональная карта с движущейся по дороге красной точкой.',
    screens: {
      'wall-center': mapPreset({
        assetId: 'map-leningrad-region',
        title: 'ЛЕНИНГРАДСКАЯ ОБЛАСТЬ',
        markerLabel: 'ОБЪЕКТ 01',
        speed: '56 КМ/Ч',
      }),
    },
    cues: [
      patchCue('advance', 'Продвинуть метку', 'wall-center', {
        markers: [
          { id: 'object-01', x: 0.68, y: 0.36, label: 'ОБЪЕКТ 01', active: true, pulse: true },
        ],
      }),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: [],
    requiredAssetIds: ['map-leningrad-region'],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's10-49',
    episode: 10,
    scene: '49',
    shootDate: '2026-09-13',
    title: 'Фроловы + Рыбаков',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Большой экран ведёт две машины, Хван анализирует видео со шлагбаума.',
    screens: {
      'wall-center': mapPreset({
        assetId: 'map-frolovy-village',
        title: 'ПОСЁЛОК / ДВА АВТОМОБИЛЯ',
        markerLabel: 'АВТО ФРОЛОВЫХ',
      }),
      'hwan-main': cctvPreset({
        assetId: 'cctv-barrier-rybakov',
        cameraId: 'GATE-04',
        location: 'ШЛАГБАУМ',
        archive: true,
      }),
    },
    cues: [
      patchCue('second-car', 'Второй автомобиль', 'wall-center', {
        markers: [
          { id: 'object-01', x: 0.52, y: 0.48, label: 'АВТО ФРОЛОВЫХ', active: true, pulse: true },
          { id: 'object-02', x: 0.38, y: 0.61, label: 'ВТОРОЕ АВТО', active: true, pulse: false },
        ],
      }),
      patchCue('freeze', 'Freeze / водитель', 'hwan-main', { playing: false, selectedCamera: 0 }),
      setModuleCue(
        'face',
        'Рыбаков / face box',
        'hwan-main',
        cctvPreset({
          assetId: 'cctv-barrier-rybakov',
          cameraId: 'GATE-04',
          location: 'РЫБАКОВ / ВОДИТЕЛЬ',
          archive: true,
        }),
      ),
    ],
    requiredScreens: ['wall-center', 'hwan-main'],
    optionalScreens: [],
    requiredAssetIds: ['map-frolovy-village', 'cctv-barrier-rybakov'],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's12-32',
    episode: 12,
    scene: '32',
    shootDate: '2026-09-13',
    title: 'Фоновая работа',
    location: 'HQ',
    sourceLevel: 'derived',
    description: 'Нейтральная системная таблица вместо неподтверждённого сюжетного контента.',
    screens: { 'wall-center': systemTablePreset('BG-08 / SYSTEM TABLE') },
    cues: [],
    requiredScreens: ['wall-center'],
    optionalScreens: ['hwan-main'],
    requiredAssetIds: [],
    optionalAssetIds: [],
    notes: ['Derived: источник не задаёт точное содержимое.'],
  }),
];
