import type { SceneDefinition } from '@gremuchaya/domain';

import {
  blackoutCue,
  cctvPreset,
  defineScene,
  dossierPreset,
  facePreset,
  idlePreset,
  interrogationPreset,
  mapPreset,
  newsPreset,
  osintPreset,
  patchCue,
  photoArchivePreset,
  printPreset,
  satellitePreset,
  setModuleCue,
  systemTablePreset,
  vehiclePreset,
} from './sceneBuilders';

const obukhovDossier = dossierPreset('obukhov', 'ОБУХОВ', {
  status: 'НАЙДЕНО',
  assets: ['photo-obukhov'],
});
const oldPhoto = osintPreset('АРХИВ / 2001', 'PHOTO', ['photo-frolova-old']);

export const september09to12Scenes: readonly SceneDefinition[] = [
  defineScene({
    id: 's04-33',
    episode: 4,
    scene: '33',
    shootDate: '2026-09-09',
    title: 'Обухов / печать',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Поиск карточки Обухова и имитация печати фотографии.',
    screens: { 'hwan-main': obukhovDossier, 'wall-center': printPreset('QUEUED') },
    cues: [
      setModuleCue('found', 'Карточка Обухова найдена', 'hwan-main', obukhovDossier),
      setModuleCue('sending', 'Отправить на печать', 'wall-center', printPreset('SENDING')),
      setModuleCue('printing', 'Печать', 'wall-center', printPreset('PRINTING')),
      setModuleCue('printed', 'Печать завершена', 'wall-center', printPreset('PRINTED')),
    ],
    requiredScreens: ['hwan-main', 'wall-center'],
    optionalScreens: [],
    requiredAssetIds: ['photo-obukhov'],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's08-16',
    episode: 8,
    scene: '16',
    shootDate: '2026-09-09',
    title: 'Захват автозака',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Архивная уличная камера показывает захват автозака.',
    screens: {
      'wall-center': cctvPreset({
        assetId: 'cctv-autozak',
        cameraId: 'CAM-0417',
        location: 'УЛИЧНЫЙ КОНТУР',
        archive: true,
      }),
    },
    cues: [
      patchCue('play', 'Запустить архив', 'wall-center', { playing: true }),
      patchCue('freeze', 'Зафиксировать кадр', 'wall-center', { playing: false }),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: ['hwan-main'],
    requiredAssetIds: ['cctv-autozak'],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's08-17',
    episode: 8,
    scene: '17/18',
    shootDate: '2026-09-09',
    title: 'Иксанов',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Новости сменяются стоп-кадром и карточкой Иксанова.',
    screens: {
      'wall-center': newsPreset('ОПЕРАТИВНЫЙ ЭФИР', 'news-iksanov'),
      'hwan-main': idlePreset('МАТЕРИАЛ ПРИНИМАЕТСЯ'),
    },
    cues: [
      setModuleCue(
        'news',
        'Новости',
        'wall-center',
        newsPreset('ОПЕРАТИВНЫЙ ЭФИР', 'news-iksanov'),
      ),
      patchCue('freeze', 'Зафиксировать эфир', 'wall-center', { mode: 'ARCHIVE' }),
      setModuleCue(
        'dossier',
        'Иксанов Георгий',
        'wall-center',
        dossierPreset('iksanov', 'ИКСАНОВ ГЕОРГИЙ', { assets: ['photo-iksanov'] }),
      ),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: ['hwan-main'],
    requiredAssetIds: ['news-iksanov', 'photo-iksanov'],
    optionalAssetIds: [],
    notes: ['Scene heading covers source scenes 8-17 and 8-18.'],
  }),
  defineScene({
    id: 's15-60',
    episode: 15,
    scene: '60',
    shootDate: '2026-09-09',
    title: 'Старое фото / Шигорев',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Поэтапный разбор старого фото с распознаванием молодого Шигорева.',
    screens: {
      'hwan-main': oldPhoto,
      'wall-center': photoArchivePreset('СТАРОЕ ФОТО / 2001', ['photo-frolova-old']),
    },
    cues: [
      setModuleCue('old-photo', 'Открыть старое фото', 'hwan-main', oldPhoto),
      patchCue('poteryaeva', 'Выделить Потеряеву', 'hwan-main', {
        stage: 'SELECT',
        selectedAssetId: 'photo-poteryaeva',
      }),
      patchCue('glukhov', 'Выделить Глухова', 'hwan-main', {
        stage: 'SELECT',
        selectedAssetId: 'photo-glukhov',
      }),
      patchCue('unknown', 'Выделить неизвестного мужчину', 'hwan-main', {
        stage: 'SELECT',
        selectedAssetId: 'photo-shigorev-young',
      }),
      setModuleCue(
        'compare',
        'Сравнение лица',
        'wall-center',
        facePreset('COMPARE', 'НЕУСТАНОВЛЕННОЕ ЛИЦО', 'photo-frolova-old', 'photo-shigorev-young'),
      ),
      setModuleCue(
        'match',
        'Совпадение: Шигорев',
        'wall-center',
        facePreset(
          'MATCH',
          'ШИГОРЕВ ДЕНИС ОЛЕГОВИЧ',
          'photo-frolova-old',
          'photo-shigorev-young',
          96.2,
        ),
      ),
    ],
    requiredScreens: ['hwan-main', 'wall-center'],
    optionalScreens: [],
    requiredAssetIds: [
      'photo-frolova-old',
      'photo-poteryaeva',
      'photo-glukhov',
      'photo-shigorev-young',
    ],
    optionalAssetIds: [],
    notes: ['Display name remains production-overridable.'],
  }),
  defineScene({
    id: 's10-22',
    episode: 10,
    scene: '22',
    shootDate: '2026-09-09',
    title: 'Переговорное устройство / Султан',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Live-вход Караева сменяется материалами осмотра по Султану.',
    screens: {
      'hwan-main': cctvPreset({
        assetId: 'cctv-gateway-karaev',
        cameraId: 'ВХОД / ШЛЮЗ 02',
        location: 'БАЗА',
      }),
    },
    cues: [
      setModuleCue(
        'gateway',
        'Караев на шлюзе',
        'hwan-main',
        cctvPreset({
          assetId: 'cctv-gateway-karaev',
          cameraId: 'ВХОД / ШЛЮЗ 02',
          location: 'БАЗА',
        }),
      ),
      setModuleCue(
        'inspection',
        'Материалы осмотра',
        'hwan-main',
        photoArchivePreset('МАТЕРИАЛЫ ОСМОТРА', [
          'photo-sultan',
          'photo-sultan-room',
          'photo-sultan-detail',
        ]),
      ),
    ],
    requiredScreens: ['hwan-main'],
    optionalScreens: ['wall-center'],
    requiredAssetIds: ['cctv-gateway-karaev', 'photo-sultan'],
    optionalAssetIds: ['photo-sultan-room', 'photo-sultan-detail'],
    notes: [],
  }),
  defineScene({
    id: 's10-47',
    episode: 10,
    scene: '47',
    shootDate: '2026-09-09',
    title: 'Положов',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Карточка Положова и связанные лица/посетители.',
    screens: {
      'hwan-main': dossierPreset('polozov', 'ПОЛОЗОВ ИГОРЬ МИХАЙЛОВИЧ', {
        status: 'СВЯЗАННЫЕ ЛИЦА / ПОСЕТИТЕЛИ',
        assets: ['photo-polozov'],
      }),
    },
    cues: [
      setModuleCue(
        'card',
        'Открыть карточку Положова',
        'hwan-main',
        dossierPreset('polozov', 'ПОЛОЗОВ ИГОРЬ МИХАЙЛОВИЧ', {
          status: 'СВЯЗАННЫЕ ЛИЦА / ПОСЕТИТЕЛИ',
          assets: ['photo-polozov'],
        }),
      ),
    ],
    requiredScreens: ['hwan-main'],
    optionalScreens: [],
    requiredAssetIds: ['photo-polozov'],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's10-45',
    episode: 10,
    scene: '45',
    shootDate: '2026-09-09',
    title: 'Фроловы / спутник',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Спутниковое сопровождение автомобиля Фроловых до дома.',
    screens: {
      'wall-center': satellitePreset({
        assetId: 'sat-frolovy-arrival',
        mode: 'TRACK',
        targetLabel: 'АВТОМОБИЛЬ ФРОЛОВЫХ',
      }),
    },
    cues: [
      setModuleCue(
        'acquire',
        'Захват автомобиля',
        'wall-center',
        satellitePreset({
          assetId: 'sat-frolovy-arrival',
          mode: 'ACQUIRE',
          targetLabel: 'АВТОМОБИЛЬ ФРОЛОВЫХ',
        }),
      ),
      setModuleCue(
        'track',
        'Сопровождение до дома',
        'wall-center',
        satellitePreset({
          assetId: 'sat-frolovy-arrival',
          mode: 'TRACK',
          targetLabel: 'АВТОМОБИЛЬ ФРОЛОВЫХ',
        }),
      ),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: ['hwan-map'],
    requiredAssetIds: ['sat-frolovy-arrival'],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's04-26',
    episode: 4,
    scene: '26',
    shootDate: '2026-09-10',
    title: 'Макеев / допрос',
    location: 'INTERROGATION',
    sourceLevel: 'kpp',
    description: 'Архивная запись допроса Макеева с timecode и микрофоном.',
    screens: {
      'interrogation-video': interrogationPreset('cctv-interrogation-makeev'),
      'interrogation-audio': idlePreset('АУДИОКАНАЛ / АРХИВ'),
    },
    cues: [
      setModuleCue(
        'archive',
        'Открыть архив допроса',
        'interrogation-video',
        interrogationPreset('cctv-interrogation-makeev'),
      ),
    ],
    requiredScreens: ['interrogation-video'],
    optionalScreens: ['interrogation-audio'],
    requiredAssetIds: ['cctv-interrogation-makeev'],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's02-14',
    episode: 2,
    scene: '14',
    shootDate: '2026-09-12',
    title: 'Общий штаб',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Все фоновые мониторы активны без сюжетных спойлеров.',
    screens: {
      'wall-left': systemTablePreset('СОБЫТИЯ'),
      'wall-center': idlePreset('ОПЕРАТИВНАЯ СВОДКА'),
      'wall-right': systemTablePreset('СОСТОЯНИЕ КАНАЛОВ'),
    },
    cues: [
      setModuleCue(
        'backgrounds',
        'Активировать фоновые контуры',
        'wall-center',
        idlePreset('ОПЕРАТИВНАЯ СВОДКА'),
      ),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: ['wall-left', 'wall-right'],
    requiredAssetIds: [],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's02-36',
    episode: 2,
    scene: '36',
    shootDate: '2026-09-12',
    title: 'Машины / Гелендвагены',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Три синхронных потока: вид сверху, карта и въезд во двор.',
    screens: {
      'wall-center': vehiclePreset('video-vehicles-overhead', 'ОБЪЕКТ 07'),
      'hwan-map': mapPreset({
        assetId: 'map-lipatov-yard',
        title: 'ДВИЖЕНИЕ К ОБЪЕКТУ',
        speed: '64 КМ/Ч',
      }),
      'wall-right': cctvPreset({
        assetId: 'cctv-lipatov-yard',
        cameraId: 'CAM-0904',
        location: 'ДВОР ЛИПАТОВА',
      }),
    },
    cues: [
      setModuleCue(
        'overhead',
        'Автомобили сверху',
        'wall-center',
        vehiclePreset('video-vehicles-overhead', 'ОБЪЕКТ 07'),
      ),
      setModuleCue(
        'route',
        'Быстро движущаяся точка',
        'hwan-map',
        mapPreset({ assetId: 'map-lipatov-yard', title: 'ДВИЖЕНИЕ К ОБЪЕКТУ', speed: '64 КМ/Ч' }),
      ),
      setModuleCue(
        'yard',
        'Машины входят во двор',
        'wall-right',
        cctvPreset({
          assetId: 'cctv-lipatov-yard',
          cameraId: 'CAM-0904',
          location: 'ДВОР ЛИПАТОВА',
        }),
      ),
    ],
    requiredScreens: ['wall-center', 'hwan-map', 'wall-right'],
    optionalScreens: [],
    requiredAssetIds: ['video-vehicles-overhead', 'map-lipatov-yard', 'cctv-lipatov-yard'],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's03-02',
    episode: 3,
    scene: '2',
    shootDate: '2026-09-12',
    title: 'Штаб ослеп',
    location: 'HQ',
    sourceLevel: 'kpp',
    description:
      'Потеря большинства сигналов и переход на единственную неподвижную метку, затем камера ГИБДД.',
    screens: {
      'hwan-map': mapPreset({
        assetId: 'map-blind-point',
        title: 'ПОСЛЕДНЯЯ ФИКСАЦИЯ',
        signal: 'НЕТ ДВИЖЕНИЯ',
      }),
      'wall-center': satellitePreset({
        assetId: 'signal-placeholder',
        mode: 'LOST',
        lossStage: 'lost',
        quality: 0,
      }),
    },
    cues: [
      setModuleCue(
        'blind',
        'Нет сигнала',
        'wall-center',
        satellitePreset({
          assetId: 'signal-placeholder',
          mode: 'LOST',
          lossStage: 'lost',
          quality: 0,
        }),
      ),
      setModuleCue(
        'gibdd',
        'Камера ГИБДД',
        'wall-center',
        cctvPreset({
          assetId: 'cctv-gibdd-lipatov',
          cameraId: 'CAM-ДПС-12',
          location: 'ПОСТ ГИБДД',
          archive: true,
        }),
      ),
    ],
    requiredScreens: ['hwan-map', 'wall-center'],
    optionalScreens: ['wall-left', 'wall-right'],
    requiredAssetIds: ['map-blind-point', 'cctv-gibdd-lipatov'],
    optionalAssetIds: ['signal-placeholder'],
    notes: [],
  }),
  defineScene({
    id: 's03-07',
    episode: 3,
    scene: '7',
    shootDate: '2026-09-12',
    title: 'Точка + адрес',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Крупный адресный takeover с активной красной точкой.',
    screens: {
      'wall-center': mapPreset({
        assetId: 'map-address-target',
        title: 'ПОСЛЕДНЯЯ ФИКСАЦИЯ',
        address: 'УЛ. ______, Д. __',
      }),
    },
    cues: [
      setModuleCue(
        'address',
        'Крупно: точка, улица, дом',
        'wall-center',
        mapPreset({
          assetId: 'map-address-target',
          title: 'ПОСЛЕДНЯЯ ФИКСАЦИЯ',
          address: 'УЛ. ______, Д. __',
        }),
      ),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: [],
    requiredAssetIds: ['map-address-target'],
    optionalAssetIds: [],
    notes: ['Address is resolved through production override.'],
  }),
  defineScene({
    id: 's07-22',
    episode: 7,
    scene: '22',
    shootDate: '2026-09-12',
    title: 'Мониторы выключены',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Основные сюжетные мониторы переходят в немедленный blackout.',
    screens: { 'wall-center': idlePreset(), 'wall-left': idlePreset(), 'wall-right': idlePreset() },
    cues: [
      blackoutCue('blackout', 'Выключить сюжетные мониторы', true),
      blackoutCue('restore', 'Восстановить контур', false),
    ],
    requiredScreens: ['wall-center'],
    optionalScreens: ['wall-left', 'wall-right'],
    requiredAssetIds: [],
    optionalAssetIds: [],
    notes: [],
  }),
  defineScene({
    id: 's12-21',
    episode: 12,
    scene: '21',
    shootDate: '2026-09-12',
    title: 'Егоров / Хмурый / Шрам / Гусейнов',
    location: 'HQ',
    sourceLevel: 'kpp',
    description: 'Последовательный просмотр пяти архивных фотографий.',
    screens: {
      'hwan-main': photoArchivePreset('ФОТОАРХИВ', [
        'photo-egorov',
        'photo-hmury',
        'photo-shram',
        'photo-guseynov-car',
        'photo-guseynov-helmet',
      ]),
    },
    cues: [
      patchCue('egorov', 'Егоров в форме сержанта', 'hwan-main', { selectedIndex: 0 }),
      patchCue('hmury', 'Хмурый', 'hwan-main', { selectedIndex: 1 }),
      patchCue('shram', 'Шрам', 'hwan-main', { selectedIndex: 2 }),
      patchCue('guseynov-car', 'Гусейнов у автомобилей', 'hwan-main', { selectedIndex: 3 }),
      patchCue('guseynov-helmet', 'Гусейнов в защитной каске', 'hwan-main', { selectedIndex: 4 }),
    ],
    requiredScreens: ['hwan-main'],
    optionalScreens: ['wall-center'],
    requiredAssetIds: [
      'photo-egorov',
      'photo-hmury',
      'photo-shram',
      'photo-guseynov-car',
      'photo-guseynov-helmet',
    ],
    optionalAssetIds: [],
    notes: [],
  }),
];
