/**
 * Public surface of the shadcn/ui component set.
 *
 * Everything here is generated by the shadcn CLI into `packages/ui/src/shadcn`
 * (see `apps/hq/components.json`), which is the only tree exempt from
 * `scripts/check-ui-boundary.mjs`. Consumers import from
 * `@gremuchaya/ui/shadcn`; they must not reach into individual files, and they
 * must never re-implement one of these components outside this package.
 *
 * These components carry the preset's own palette (`--background`,
 * `--primary`, `--ui-accent`, …), which is separate from the terminal design
 * tokens. Use `Terminal*` primitives for the operational shell and this set
 * where a richer control is genuinely needed.
 */
export * from './utils.js';
export * from './button.js';
